[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "philosopher-chat"
version = "0.1.0"
authors = [{ name = "Erfan Moosavi", email = "erfanmoosavi84@gmail.com" }]
description = "Chat with philosophers!"
readme = "README.md"
license = {text = "MIT"}  # Fixed license format
requires-python = ">=3.8"
dependencies = [
  "openai>=1.0.0",
  "pyyaml>=6.0",
]

[tool.setuptools.packages.find]
where = ["src"]